// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[repr(u8)]
#[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
pub enum Dir {
    None,
    Up,
    Down,
    Left,
    Right,
}
impl ::core::fmt::Debug for Dir {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        match self {
            Dir::None => f.debug_tuple("Dir::None").finish(),
            Dir::Up => f.debug_tuple("Dir::Up").finish(),
            Dir::Down => f.debug_tuple("Dir::Down").finish(),
            Dir::Left => f.debug_tuple("Dir::Left").finish(),
            Dir::Right => f.debug_tuple("Dir::Right").finish(),
        }
    }
}
impl Dir {
    #[doc(hidden)]
    pub unsafe fn _lift(val: u8) -> Dir {
        if !cfg!(debug_assertions) {
            return ::core::mem::transmute(val);
        }
        match val {
            0 => Dir::None,
            1 => Dir::Up,
            2 => Dir::Down,
            3 => Dir::Left,
            4 => Dir::Right,
            _ => panic!("invalid enum discriminant"),
        }
    }
}
#[derive(Clone, Copy)]
pub enum Cell {
    Empty,
    Player(u8),
    PlayerClaimed(u8),
}
impl ::core::fmt::Debug for Cell {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        match self {
            Cell::Empty => f.debug_tuple("Cell::Empty").finish(),
            Cell::Player(e) => f.debug_tuple("Cell::Player").field(e).finish(),
            Cell::PlayerClaimed(e) => f.debug_tuple("Cell::PlayerClaimed").field(e).finish(),
        }
    }
}
#[derive(Clone)]
pub struct Brain {
    pub facing: Dir,
    pub memory: _rt::Vec<u8>,
}
impl ::core::fmt::Debug for Brain {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Brain")
            .field("facing", &self.facing)
            .field("memory", &self.memory)
            .finish()
    }
}
#[derive(Clone)]
pub struct Action {
    pub move_: Dir,
    pub brain: Option<Brain>,
}
impl ::core::fmt::Debug for Action {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Action")
            .field("move", &self.move_)
            .field("brain", &self.brain)
            .finish()
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_get_name_cabi<T: Guest>() -> *mut u8 {
    #[cfg(target_arch = "wasm32")]
    _rt::run_ctors_once();
    let result0 = T::get_name();
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec2 = (result0.into_bytes()).into_boxed_slice();
    let ptr2 = vec2.as_ptr().cast::<u8>();
    let len2 = vec2.len();
    ::core::mem::forget(vec2);
    *ptr1
        .add(::core::mem::size_of::<*const u8>())
        .cast::<usize>() = len2;
    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
    ptr1
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_get_name<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0
        .add(::core::mem::size_of::<*const u8>())
        .cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_step_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
    arg2: i32,
    arg3: i32,
    arg4: i32,
    arg5: i32,
    arg6: *mut u8,
    arg7: usize,
    arg8: i32,
    arg9: i32,
) -> *mut u8 {
    #[cfg(target_arch = "wasm32")]
    _rt::run_ctors_once();
    let base4 = arg0;
    let len4 = arg1;
    let mut result4 = _rt::Vec::with_capacity(len4);
    for i in 0..len4 {
        let base = base4.add(i * 2);
        let e4 = {
            let l0 = i32::from(*base.add(0).cast::<u8>());
            let v3 = match l0 {
                0 => Cell::Empty,
                1 => {
                    let e3 = {
                        let l1 = i32::from(*base.add(1).cast::<u8>());
                        l1 as u8
                    };
                    Cell::Player(e3)
                }
                n => {
                    debug_assert_eq!(n, 2, "invalid enum discriminant");
                    let e3 = {
                        let l2 = i32::from(*base.add(1).cast::<u8>());
                        l2 as u8
                    };
                    Cell::PlayerClaimed(e3)
                }
            };
            v3
        };
        result4.push(e4);
    }
    _rt::cabi_dealloc(base4, len4 * 2, 1);
    let len5 = arg7;
    let result6 = T::step(
        result4,
        arg2 as u8,
        (arg3 as u32, arg4 as u32),
        Brain {
            facing: Dir::_lift(arg5 as u8),
            memory: _rt::Vec::from_raw_parts(arg6.cast(), len5, len5),
        },
        arg8 as u32,
        arg9 as u32,
    );
    let ptr7 = (&raw mut _RET_AREA.0).cast::<u8>();
    let Action {
        move_: move_8,
        brain: brain8,
    } = result6;
    *ptr7.add(0).cast::<u8>() = (move_8.clone() as i32) as u8;
    match brain8 {
        Some(e) => {
            *ptr7.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
            let Brain {
                facing: facing9,
                memory: memory9,
            } = e;
            *ptr7
                .add(2 * ::core::mem::size_of::<*const u8>())
                .cast::<u8>() = (facing9.clone() as i32) as u8;
            let vec10 = (memory9).into_boxed_slice();
            let ptr10 = vec10.as_ptr().cast::<u8>();
            let len10 = vec10.len();
            ::core::mem::forget(vec10);
            *ptr7
                .add(4 * ::core::mem::size_of::<*const u8>())
                .cast::<usize>() = len10;
            *ptr7
                .add(3 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>() = ptr10.cast_mut();
        }
        None => {
            *ptr7.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
        }
    };
    ptr7
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_step<T: Guest>(arg0: *mut u8) {
    let l0 = i32::from(*arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
    match l0 {
        0 => {}
        _ => {
            let l1 = *arg0
                .add(3 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l2 = *arg0
                .add(4 * ::core::mem::size_of::<*const u8>())
                .cast::<usize>();
            let base3 = l1;
            let len3 = l2;
            _rt::cabi_dealloc(base3, len3 * 1, 1);
        }
    }
}
pub trait Guest {
    fn get_name() -> _rt::String;
    fn step(
        grid: _rt::Vec<Cell>,
        player_id: u8,
        pos: (u32, u32),
        brain: Brain,
        width: u32,
        height: u32,
    ) -> Action;
}
#[doc(hidden)]
macro_rules! __export_world_strategy_plugin_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "get-name")] unsafe extern "C" fn
        export_get_name() -> * mut u8 { unsafe { $($path_to_types)*::
        _export_get_name_cabi::<$ty > () } } #[unsafe (export_name =
        "cabi_post_get-name")] unsafe extern "C" fn _post_return_get_name(arg0 : * mut
        u8,) { unsafe { $($path_to_types)*:: __post_return_get_name::<$ty > (arg0) } }
        #[unsafe (export_name = "step")] unsafe extern "C" fn export_step(arg0 : * mut
        u8, arg1 : usize, arg2 : i32, arg3 : i32, arg4 : i32, arg5 : i32, arg6 : * mut
        u8, arg7 : usize, arg8 : i32, arg9 : i32,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_step_cabi::<$ty > (arg0, arg1, arg2, arg3, arg4,
        arg5, arg6, arg7, arg8, arg9) } } #[unsafe (export_name = "cabi_post_step")]
        unsafe extern "C" fn _post_return_step(arg0 : * mut u8,) { unsafe {
        $($path_to_types)*:: __post_return_step::<$ty > (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_strategy_plugin_cabi;
#[cfg_attr(target_pointer_width = "64", repr(align(8)))]
#[cfg_attr(target_pointer_width = "32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 5 * ::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea =
    _RetArea([::core::mem::MaybeUninit::uninit(); 5 * ::core::mem::size_of::<*const u8>()]);
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod game {
    pub mod strategy_plugin {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod logger {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            #[allow(unused_unsafe, clippy::all)]
            pub fn error(msg: &str) -> () {
                unsafe {
                    let vec0 = msg;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "game:strategy-plugin/logger")]
                    unsafe extern "C" {
                        #[link_name = "error"]
                        fn wit_import1(_: *mut u8, _: usize);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) {
                        unreachable!()
                    }
                    unsafe { wit_import1(ptr0.cast_mut(), len0) };
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn warn(msg: &str) -> () {
                unsafe {
                    let vec0 = msg;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "game:strategy-plugin/logger")]
                    unsafe extern "C" {
                        #[link_name = "warn"]
                        fn wit_import1(_: *mut u8, _: usize);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) {
                        unreachable!()
                    }
                    unsafe { wit_import1(ptr0.cast_mut(), len0) };
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn info(msg: &str) -> () {
                unsafe {
                    let vec0 = msg;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "game:strategy-plugin/logger")]
                    unsafe extern "C" {
                        #[link_name = "info"]
                        fn wit_import1(_: *mut u8, _: usize);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) {
                        unreachable!()
                    }
                    unsafe { wit_import1(ptr0.cast_mut(), len0) };
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn debug(msg: &str) -> () {
                unsafe {
                    let vec0 = msg;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "game:strategy-plugin/logger")]
                    unsafe extern "C" {
                        #[link_name = "debug"]
                        fn wit_import1(_: *mut u8, _: usize);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) {
                        unreachable!()
                    }
                    unsafe { wit_import1(ptr0.cast_mut(), len0) };
                }
            }
        }
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod random {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[allow(unused_unsafe, clippy::all)]
            pub fn from_vec(range: &[u32]) -> Option<u32> {
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 8]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
                    let vec0 = range;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "game:strategy-plugin/random")]
                    unsafe extern "C" {
                        #[link_name = "from-vec"]
                        fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
                    let l3 = i32::from(*ptr1.add(0).cast::<u8>());
                    let result5 = match l3 {
                        0 => None,
                        1 => {
                            let e = {
                                let l4 = *ptr1.add(4).cast::<i32>();
                                l4 as u32
                            };
                            Some(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result5
                }
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::string::String;
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_strategy_plugin_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_strategy_plugin_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_strategy_plugin_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.41.0:game:strategy-plugin:strategy-plugin:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 563] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xad\x03\x01A\x02\x01\
A\x14\x01m\x05\x04none\x02up\x04down\x04left\x05right\x03\0\x03dir\x03\0\0\x01q\x03\
\x05empty\0\0\x06player\x01}\0\x0eplayer-claimed\x01}\0\x03\0\x04cell\x03\0\x02\x01\
p}\x01r\x02\x06facing\x01\x06memory\x04\x03\0\x05brain\x03\0\x05\x01k\x06\x01r\x02\
\x04move\x01\x05brain\x07\x03\0\x06action\x03\0\x08\x01B\x05\x01@\x01\x03msgs\x01\
\0\x04\0\x05error\x01\0\x04\0\x04warn\x01\0\x04\0\x04info\x01\0\x04\0\x05debug\x01\
\0\x03\0\x1bgame:strategy-plugin/logger\x05\x0a\x01B\x04\x01py\x01ky\x01@\x01\x05\
range\0\0\x01\x04\0\x08from-vec\x01\x02\x03\0\x1bgame:strategy-plugin/random\x05\
\x0b\x01@\0\0s\x04\0\x08get-name\x01\x0c\x01p\x03\x01o\x02yy\x01@\x06\x04grid\x0d\
\x09player-id}\x03pos\x0e\x05brain\x06\x05widthy\x06heighty\0\x09\x04\0\x04step\x01\
\x0f\x04\0$game:strategy-plugin/strategy-plugin\x04\0\x0b\x15\x01\0\x0fstrategy-\
plugin\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227\
.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}

impl Dir {
    pub fn right(&self) -> Self {
        match self {
            Self::None => Self::None,
            Self::Up => Self::Right,
            Self::Down => Self::Left,
            Self::Left => Self::Up,
            Self::Right => Self::Down,
        }
    }

    pub fn left(&self) -> Self {
        match self {
            Self::None => Self::None,
            Self::Up => Self::Left,
            Self::Down => Self::Right,
            Self::Left => Self::Down,
            Self::Right => Self::Up,
        }
    }

    pub fn from_to(from: (u32, u32), to: (u32, u32)) -> Self {
        let dx: i32 = to.0.cast_signed() - from.0.cast_signed();
        let dy: i32 = to.1.cast_signed() - from.1.cast_signed();

        match (dx, dy) {
            (0, 0) => Self::None,
            (1, 0) => Self::Right,
            (-1, 0) => Self::Left,
            (0, 1) => Self::Down,
            (0, -1) => Self::Up,
            _ => panic!("From and to are not adjacent"),
        }
    }
}

impl std::ops::Add<Dir> for (u32, u32) {
    type Output = Self;

    fn add(self, rhs: Dir) -> Self::Output {
        match rhs {
            Dir::None => self,
            Dir::Up => (self.0, self.1 - 1),
            Dir::Down => (self.0, self.1 + 1),
            Dir::Left => (self.0 - 1, self.1),
            Dir::Right => (self.0 + 1, self.1),
        }
    }
}

pub trait Pos {
    fn neighbours(self, width: u32, height: u32) -> Vec<(u32, u32)>;

    fn can_move(&self, grid: &[Cell], dir: Dir, width: u32, height: u32, id: u8) -> bool;
}

impl Pos for (u32, u32) {
    fn neighbours(self, width: u32, height: u32) -> Vec<Self> {
        let mut neighbours_positions = Vec::new();

        if self.0 > 0 {
            neighbours_positions.push(self + Dir::Left);
        }

        if self.0 < width - 1 {
            neighbours_positions.push(self + Dir::Right);
        }

        if self.1 > 0 {
            neighbours_positions.push(self + Dir::Up);
        }

        if self.1 < height - 1 {
            neighbours_positions.push(self + Dir::Down);
        }

        neighbours_positions
    }

    fn can_move(&self, grid: &[Cell], dir: Dir, width: u32, height: u32, id: u8) -> bool {
        if self.0 == 0 && matches!(dir, Dir::Left)
            || self.0 == width - 1 && matches!(dir, Dir::Right)
            || self.1 == 0 && matches!(dir, Dir::Up)
            || self.1 == height - 1 && matches!(dir, Dir::Down)
        {
            return false;
        }

        let new_pos = *self + dir;

        match grid[(new_pos.1 * width + new_pos.0) as usize] {
            Cell::Empty => true,
            Cell::Player(player_id) | Cell::PlayerClaimed(player_id) if player_id == id => true,
            _ => false,
        }
    }
}

impl Action {
    pub fn new(move_dir: Dir, brain: Option<Brain>) -> Self {
        Self {
            move_: move_dir,
            brain,
        }
    }
}

impl From<Dir> for Action {
    fn from(value: Dir) -> Self {
        Self {
            move_: value,
            brain: None,
        }
    }
}
